apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: sdp-test
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: myharbor.zznode.com/sdp_test/auth:v1
        imagePullPolicy: Always       
        ports:
        - containerPort: 8989
        env:
        - name: "uri"
          value: "http://config-service:8901"
        - name: "port"
          value: "8989"
        - name: "defaultZone"
          value: "http://eureka-service:8761/eureka/"
        - name: "redisIp"
          value: "redis-service:6379"
        - name: "mysqlIp"
          value: "jdbc:mysql://mysql-service:3306/esi?useUnicode=true&characterEncoding=utf8"
      restartPolicy: Always
      imagePullSecrets:
        - name: myharbor