apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sdp-test
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: myharbor.zznode.com/sdp_test/eureka-server:v1
        imagePullPolicy: Always       
        ports:
        - containerPort: 8761
        env:
        - name: "port"
          value: "8761"
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
          timeoutSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: myharbor