apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
  namespace: sdp-test
  labels:
    app: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: hadoop
        image: myharbor.zznode.com/sdp_test/hadoop:v1
        imagePullPolicy: Always       
        ports:
        - containerPort: 9501
        env:
        - name: "uri"
          value: "http://config-service:8901"
        - name: "port"
          value: "9501"
        - name: "defaultZone"
          value: "http://eureka-service:8761/eureka/"
        - name: "redisIp"
          value: "redis-service:6379"
        - name: "mysqlIp"
          value: "jdbc:mysql://mysql-service:3306/esi?useUnicode=true&characterEncoding=utf8"
      restartPolicy: Always
      imagePullSecrets:
        - name: myharbor