apiVersion: v1
kind: Service
metadata:
  name: platform-webadmin-service	#Service 的名称
  namespace: sdp-test
  labels:     	#Service 自己的标签
    app: platform-webadmin	#为该 Service 设置 key 为 app，value 为 nginx 的标签
spec:	    #这是关于该 Service 的定义，描述了 Service 如何选择 Pod，如何被访问
  selector:	    #标签选择器
    app: platform-webadmin	#选择包含标签 app:nginx 的 Pod
  ports:
  - name: platform-webadmin-port	#端口的名字
    protocol: TCP	    #协议类型 TCP/UDP
    port: 8803	        #集群内的其他容器组可通过 80 端口访问 Service
    #nodePort: 38761   #通过任意节点的 32600 端口访问 Service
    targetPort: 8803	#将请求转发到匹配 Pod 的 80 端口
  type: ClusterIP	#Serive的类型，ClusterIP/NodePort/LoaderBalancer

