apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
  namespace: sdp-test
  labels:
    app: platform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-app
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      containers:
      - name: platform-app
        image: myharbor.zznode.com/sdp_test/platform-app:v1
        imagePullPolicy: Always       
        ports:
        - containerPort: 8804
        env:
        - name: "uri"
          value: "http://config-service:8901"
        - name: "port"
          value: "8804"
        - name: "defaultZone"
          value: "http://eureka-service:8761/eureka/"
        - name: "redisIp"
          value: "redis-service:6379"
        - name: "mysqlIp"
          value: "jdbc:mysql://mysql-service:3306/esi?useUnicode=true&characterEncoding=utf8"
      restartPolicy: Always
      imagePullSecrets:
        - name: myharbor