apiVersion: v1
kind: Pod
metadata:
  name: webadmin
  labels:
    name: webadmin
spec:
  containers:
  - name: webadmin
    image: myharbor.zznode.com/sdp_test/webadmin:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    imagePullPolicy: Always
    ports:
      - containerPort: 8088

  imagePullSecrets:
    - name: myharbor

---
apiVersion: v1
kind: Service
metadata:
  name: webadmin
spec:
  selector:
    name: webadmin
  
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webadmin
  labels:
    name: webadmin
spec:
  rules:
  - host: sdp.zznode.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webadmin
            port: 
              number: 8088


